# -*- coding: utf-8 -*-
"""r-p-s.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xj8Mp_lrrSBTv2EAkmm2nt4BELZz6iLj
"""

import random
def play():
    user = input("What's your choice? 'r' for rock, 'p' for paper, 's' for scissors\n")
    computer = random.choice(['r', 'p', 's'])
    if user == computer:
        return 'It\'s a tie'
    # r > s, s > p, p > r
    if is_win(user, computer):
        return 'You won!'
    return 'You lost!'
def is_win(player, opponent):
    # return true if player wins
    # r > s, s > p, p > r
    if (player == 'r' and opponent == 's') or (player == 's' and opponent == 'p') or (player == 'p' and opponent == 'r'):
        return True
print(play())